services:
  - type: web
    name: geoattend
    env: node
    plan: free
    buildCommand: ""
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
